name: PR build

on:
  pull_request:
    branches: ["main"]
    paths: ["src/**/*"]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        version: ['6.0', '7.0']
    name: PR build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.version }}
          dotnet-quality: 'ga'

      - name: Install dependencies
        run: dotnet restore Results.Immutable.sln
        working-directory: src

      - name: Build
        run: dotnet build Results.Immutable.sln --configuration Debug --no-restore -f net${{ matrix.version }}
        working-directory: src

      - name: Test & analyze coverage
        run: dotnet test -c Debug -f net${{ matrix.version }} -p:coverletOutput=../coverage/lcov.info -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:Exclude=\"\" **/*[Tt]ests.csproj
        working-directory: src

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Record LCOV
        uses: zgosalvez/github-actions-report-lcov@v4.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ./src/coverage/lcov.*.info
          minimum-coverage: 85
          update-comment: true
    