name: PR build

on:
  pull_request:
    branches: ["main"]
    paths: ["src/**/*"]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    name: PR build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
          dotnet-quality: 'ga'

      - name: Install dependencies
        run: dotnet restore Results.Immutable.sln
        working-directory: src

      - name: Build
        run: dotnet build Results.Immutable.sln --configuration Debug --no-restore
        working-directory: src

      - name: Test & analyze coverage
        run: dotnet test -c Debug -p:coverletOutput=../coverage/lcov.info -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:Exclude=\"\" src/**/*[Tt]ests.csproj

      - name: Generate code coverage report (.NET 6.0)
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./src/coverage/lcov.net6.0.info
          title: Code coverage summary (.NET 6)
      
      - name: Generate code coverate report (.NET 7.0)
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./src/coverage/lcov.net7.0.info
          title: Code coverage summary (.NET 7)