name: Version

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release type
        type: choice
        default: stable
        options:
          - stable
          - alpha
          - beta
          - rc

env:
  params: ${{ inputs.release-type == 'stable' && '--conventional-graduate' || format('--conventional-prerelease --preid {0}', inputs.release-type) }}

jobs:
  preview:
    name: Preview versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --immutable
      - name: Preview proposed versions
        run: |
          echo "n" | yarn lerna version ${{ env.params }} >> $GITHUB_STEP_SUMMARY

  version:
    name: Update versions
    needs: preview
    environment: versioning
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install --immutable

      - name: Setting branch name
        run: echo "branch=version/$(date +"%d-%m-%y-%H-%M-%S")" >> $GITHUB_OUTPUT
        id: branch-name

      - name: Creating branch
        run: |
          git switch -c ${{ steps.branch-name.outputs.branch }}
          git push --set-upstream origin ${{ steps.branch-name.outputs.branch }}

      - name: Set credentials
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Action"

      - name: Preview proposed versions
        run: |
          yarn lerna version -y --create-release github ${{ env.params }}

      - name: Create Pull Request
        run: |
          echo -e "Review Pull Request:\n" >> $GITHUB_STEP_SUMMARY
          gh pr create --fill-first >> $GITHUB_STEP_SUMMARY
